parameters:
- name: afectacion
  displayName: ¿El Cambio genera Interrupción / Degradación en aplicaciones o es necesario ejecutarlo en una ventana programada?
  type: string
  default: No
  values:
  - Si
  - No

resources:
  repositories:
    - repository: Cloud_cld0002001_arq_despliegues_cloud
      type: git
      ref: refs/heads/trunk
      name: Cloud_cld0002001_arq_despliegues_cloud

    - repository: Template_DevSecOps_IaC
      type: git
      ref: refs/heads/trunk
      name: Template_DevSecOps_IaC

trigger:
  branches:
    include:
      - trunk

variables:
  afectacion: '${{parameters.afectacion}}'
  application-code: 'aw0946001'
  project-name: 'serviciosfactoring'
  evc: 'EVC Gestion de Flujos'
  cost-center: 'c103500007'
  business-service: 'productos-de-financiacion'
  cloudformation-stack-name: '$(application-code)-$(project-name)'


  cloudformation-template-kms: '$(System.DefaultWorkingDirectory)/cloudformation/template-kms.yaml'
  cloudformation-params-kms: '$(System.DefaultWorkingDirectory)/config/params-kms.json'

  cloudformation-template-s3: '$(System.DefaultWorkingDirectory)/cloudformation/template-s3.yaml'
  cloudformation-params-s3: '$(System.DefaultWorkingDirectory)/config/params-s3.json'

  cloudformation-template-sg: '$(System.DefaultWorkingDirectory)/cloudformation/template-sg.yaml'
  cloudformation-params-sg: '$(System.DefaultWorkingDirectory)/config/params-sg.json'

  cloudformation-template-sm: '$(System.DefaultWorkingDirectory)/cloudformation/template-sm.yaml'
  cloudformation-params-sm: '$(System.DefaultWorkingDirectory)/config/params-sm.json'

  cloudformation-template-reporting: '$(System.DefaultWorkingDirectory)/cloudformation/template-reporting.yaml'
  cloudformation-params-reporting: '$(System.DefaultWorkingDirectory)/config/params-reporting.json'

  cloudformation-template-ec2: '$(System.DefaultWorkingDirectory)/cloudformation/template-ec2.yaml'
  cloudformation-params-ec2: '$(System.DefaultWorkingDirectory)/config/params-ec2.json'    


  namespace: $(project-name)
  ruta: $(project-name)

stages:

  - stage: linters
    displayName: Validations
    jobs:
      - template: /Deployment/validations.yaml@Cloud_cld0002001_arq_despliegues_cloud

  - stage: code_scan_iac_dev
    displayName: Code Scan IaC Dev
    variables:
      - group: aw0946001-serviciosfactoring-variables-dev-aws
    jobs:
      - template: validations.yaml@Template_DevSecOps_IaC
        parameters:
          resources: [s3,kms,sm,sg,reporting,ec2]

  - stage: deploy_dev
    displayName: Deploy dev
    dependsOn: [code_scan_iac_dev, linters]   
    variables:
      - group: aw0946001-serviciosfactoring-variables-dev-aws
    
    jobs:  
        - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
          parameters:
            account: bancolombia-productos-financiacion-dev-aws
            pool: Release-cloud
            name: '$(cloudformation-stack-name)-$(env)-kms'
            resource: kms
            jobname: kms

        - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
          parameters:
            account: bancolombia-productos-financiacion-dev-aws
            pool: Release-cloud
            name: '$(cloudformation-stack-name)-$(env)-s3'
            resource: s3
            jobname: s3 

        - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
          parameters:
            account: bancolombia-productos-financiacion-dev-aws
            pool: Release-cloud
            name: '$(cloudformation-stack-name)-$(env)-sg'
            resource: sg
            jobname: sg          

        - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
          parameters:
            account: bancolombia-productos-financiacion-dev-aws
            pool: Release-cloud
            name: '$(cloudformation-stack-name)-$(env)-sm'
            resource: sm
            jobname: sm 
            depends: 
            - kms     

        - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
          parameters:
            account: bancolombia-productos-financiacion-dev-aws
            pool: Release-cloud
            name: '$(cloudformation-stack-name)-$(env)-reporting'
            resource: reporting
            jobname: reporting
            depends: 
            - sg                     

        - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
          parameters:
            account: bancolombia-productos-financiacion-dev-aws
            pool: Release-cloud
            name: '$(cloudformation-stack-name)-$(env)-ec2'
            resource: ec2
            jobname: ec2       
            depends: 
            - sm  
            - sg 
            - kms   
            - s3   

      

  - stage: code_scan_iac_qa
    displayName: Code Scan IaC qa
    variables:
      - group: aw0946001-serviciosfactoring-variables-qa-aws
        
    jobs:
      - template: validations.yaml@Template_DevSecOps_IaC
        parameters:
          resources: [s3,kms,sm,sg,reporting,ec2]
  - stage: deploy_qa
    displayName: Deploy qa
    dependsOn: [code_scan_iac_qa, linters]   
    variables:
      - group: aw0946001-serviciosfactoring-variables-qa-aws
      
    jobs:  
      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-qa-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-kms'
          resource: kms
          jobname: kms

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-qa-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-s3'
          resource: s3
          jobname: s3 

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-qa-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-sg'
          resource: sg
          jobname: sg          

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-qa-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-sm'
          resource: sm
          jobname: sm
          depends: 
          - kms     

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-qa-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-reporting'
          resource: reporting
          jobname: reporting
          depends: 
          - sg                     

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-qa-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-ec2'
          resource: ec2
          jobname: ec2       
          depends: 
          - sm  
          - sg 
          - kms
          - s3    


  - stage: code_scan_iac_pdn
    displayName: Code Scan IaC pdn
    variables:
      - group: aw0946001-serviciosfactoring-variables-pdn-aws
      
    jobs:
      - template: validations.yaml@Template_DevSecOps_IaC
        parameters:
          resources: [kms,s3,sg,sm,reporting,ec2]
  - stage: deploy_pdn
    displayName: Deploy pdn
    dependsOn: [code_scan_iac_pdn, linters]   
    variables:
      - group: aw0946001-serviciosfactoring-variables-pdn-aws
        
    jobs:  
      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-pdn-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-kms'
          resource: kms
          jobname: kms

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-pdn-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-s3'
          resource: s3
          jobname: s3 

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-pdn-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-sg'
          resource: sg
          jobname: sg          

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-pdn-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-sm'
          resource: sm
          jobname: sm 
          depends: 
          - kms 

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-pdn-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-reporting'
          resource: reporting
          jobname: reporting
          depends: 
          - sg                     

      - template: /Deployment/deployment.yaml@Cloud_cld0002001_arq_despliegues_cloud
        parameters:
          account: bancolombia-productos-financiacion-pdn-aws
          pool: Release-cloud
          name: '$(cloudformation-stack-name)-$(env)-ec2'
          resource: ec2
          jobname: ec2       
          depends: 
          - sm  
          - sg 
          - kms
          - s3      
      